# Converts adoc files to html and push to gh-pages branch to update GitHub Pages

name: asciidoctor

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Asciidoctor Setup
      uses: reitzig/actions-asciidoctor@v1.0.0
      with:
        version: 2.0.10
        # Any options every run of asciidoctor should use.
        #Example: "-a experimental=true -d inline"
        #options:

    - name: Performs the adoc to html convertion and publish to GitHub Pages
      run: ./gh-pages.sh
